#!/usr/bin/env python3
"""A2 Q2 Option A: train the LightGBM LambdaRank re-ranker and report before/after metrics.

Two-stage pipeline, per the design decision recorded in CONTEXT.md: stage 1 is the impression's
own shown slate (which is what both Codabench competitions score, and what A1's full-catalog
retrieval could not supply -- its recall@200 of 2.01% leaves the clicked article out of the pool
98% of the time), and A1's BM25 and embedding scorers contribute their *scores* as features rather
than their shortlist. "Before" in the Q2.4 table is therefore each of those A1 scorers used alone,
which is exactly the system A1 submitted.

Usage:
    python scripts/run_reranker.py --dataset ebnerd
    python scripts/run_reranker.py --dataset mind --limit 20000      # smoke test
    python scripts/run_reranker.py --dataset ebnerd --submission-safe # drop click-derived features

Writes models/<dataset>/reranker.lgb (git-ignored) and
results/<dataset>/rerank_before_after.{json,md}.
"""
import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ire_a1.eval import bootstrap_ci, ranking_metrics  # noqa: E402
from ire_a1.reranker import LambdaRanker, MatrixBuilder, RankingMatrix  # noqa: E402

METRICS = ["auc", "mrr", "ndcg@5", "ndcg@10"]


def score_metrics(matrix: RankingMatrix, scores: np.ndarray, n_boot: int) -> dict:
    """Per-impression AUC/MRR/nDCG, aggregated with a bootstrap CI -- the same functions and the
    same treatment of undefined impressions as A1's run_eval.py, so the before/after rows and
    A1's reported numbers are directly comparable rather than merely similar."""
    per_impression: list[dict] = []
    offset = 0
    for size in matrix.groups:
        sl = slice(offset, offset + size)
        per_impression.append(ranking_metrics(scores[sl].tolist(), matrix.y[sl].tolist()))
        offset += size

    out = {}
    for metric in METRICS:
        values = [row[metric] for row in per_impression if row[metric] is not None]
        out[metric] = bootstrap_ci(values, n_boot=n_boot)
    return out


def build_matrices(args, builder: MatrixBuilder, ds_dir: Path) -> dict[str, RankingMatrix]:
    matrices = {}
    for split in ("train", "val", "test"):
        impressions = pl.read_parquet(ds_dir / f"impressions_{split}.parquet")
        if args.limit:
            impressions = impressions.head(args.limit)
        t0 = time.time()
        matrix = builder.transform(impressions)
        if args.submission_safe:
            matrix = matrix.select(builder.submission_safe_feature_names)
        print(f"  {split:5} {matrix.n_rows:>9,} rows / {matrix.n_impressions:>7,} impressions "
              f"({time.time() - t0:5.1f}s)")
        matrices[split] = matrix
    return matrices


def write_comparison(results_dir: Path) -> Path | None:
    """Regenerate the cross-run table from every rerank_before_after*.json on disk, so the four
    runs (two datasets x full/submission-safe) stay in one place as each finishes."""
    runs = sorted(results_dir.glob("*/rerank_before_after*.json"))
    if not runs:
        return None
    rows = []
    for path in runs:
        payload = json.loads(path.read_text())
        for method, metrics in payload["metrics"].items():
            rows.append({
                "dataset": payload["dataset"],
                "variant": "submission-safe" if payload["submission_safe"] else "full",
                "method": method, "n_features": payload["n_features"],
                **{m: metrics[m]["mean"] for m in METRICS},
                "ci_low": metrics["auc"]["ci_low"], "ci_high": metrics["auc"]["ci_high"],
            })

    lines = [
        "# Q2 re-ranker: before and after",
        "",
        "Generated by `scripts/run_reranker.py`. Test split, bootstrap 95% CI on AUC.",
        "",
        "**Before** is each A1 stage-1 scorer used alone -- `bm25_score` and `embed_cos` are the",
        "systems A1 actually submitted, and they appear here as features of the re-ranker rather",
        "than as a separate retrieval stage (see the candidate-set decision in `CONTEXT.md`).",
        "",
        "**Submission-safe** drops the five click-derived features, because neither Codabench test",
        "set ships click labels. It is the variant that could actually be submitted.",
        "",
        "| Dataset | Variant | Method | AUC | 95% CI | MRR | nDCG@5 | nDCG@10 |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        name = (f"**{row['method']}**" if row["method"].startswith("reranker")
                else f"`{row['method']}`")
        lines.append(
            f"| {row['dataset']} | {row['variant']} | {name} | {row['auc']:.4f} | "
            f"[{row['ci_low']:.3f}, {row['ci_high']:.3f}] | {row['mrr']:.4f} | "
            f"{row['ndcg@5']:.4f} | {row['ndcg@10']:.4f} |")

    out = results_dir / "rerank_comparison.md"
    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset", choices=["ebnerd", "mind"], required=True)
    parser.add_argument("--processed-dir", type=Path, default=Path("data/processed"))
    parser.add_argument("--embeddings-file", default="embeddings_mpnet.parquet")
    parser.add_argument("--models-dir", type=Path, default=Path("models"))
    parser.add_argument("--results-dir", type=Path, default=Path("results"))
    parser.add_argument("--num-boost-round", type=int, default=1000)
    parser.add_argument("--early-stopping-rounds", type=int, default=50)
    parser.add_argument("--n-boot", type=int, default=1000)
    parser.add_argument("--submission-safe", action="store_true",
                        help="train only on features computable when the scored impressions have "
                             "no click labels, which is the case for both Codabench test sets")
    parser.add_argument("--limit", type=int, default=None,
                        help="only use the first N impressions per split (smoke test)")
    args = parser.parse_args()

    ds_dir = args.processed_dir / args.dataset
    articles = pl.read_parquet(ds_dir / "articles.parquet")
    history = pl.read_parquet(ds_dir / "user_history.parquet")
    index_impressions = pl.concat(
        [pl.read_parquet(ds_dir / f"impressions_{s}.parquet") for s in ("train", "val", "test")]
    )
    embeddings_path = ds_dir / args.embeddings_file
    if not embeddings_path.exists():
        print(f"note: {embeddings_path.name} missing -- embedding similarity omitted")
        embeddings_path = None

    print(f"Building feature sources for {args.dataset} ...")
    builder = MatrixBuilder.build(articles=articles, history=history,
                                  index_impressions=index_impressions,
                                  embeddings_path=embeddings_path)
    matrices = build_matrices(args, builder, ds_dir)
    train, valid, test = matrices["train"], matrices["val"], matrices["test"]
    print(f"  {len(train.feature_names)} features"
          + (" (submission-safe subset)" if args.submission_safe else ""))

    print("\nTraining LambdaRank ...")
    t0 = time.time()
    model = LambdaRanker.train(train, valid, num_boost_round=args.num_boost_round,
                               early_stopping_rounds=args.early_stopping_rounds)
    train_s = time.time() - t0
    print(f"  {model.booster.best_iteration} rounds kept (of {args.num_boost_round}) "
          f"in {train_s:.1f}s")

    # "Before" is each A1 stage-1 scorer alone -- the system A1 actually submitted.
    baselines = {name: test.column(name) for name in builder.similarity_features
                 if name in test.feature_names}
    results = {name: score_metrics(test, scores, args.n_boot) for name, scores in baselines.items()}
    results["reranker"] = score_metrics(test, model.predict(test), args.n_boot)
    # Reported as its own row rather than folded into the model: a GBDT cannot reproduce a
    # continuous input feature's ordering because it bins its inputs, and breaking the resulting
    # ties with the strongest continuous feature recovers part of that loss. Showing both keeps
    # the effect visible instead of quietly improving the headline.
    if best_similarity := next((n for n in ("embed_cos", "bm25_score")
                                if n in test.feature_names), None):
        results[f"reranker + {best_similarity} tie-break"] = score_metrics(
            test, model.predict(test, tie_breaker=best_similarity), args.n_boot)

    importance = model.feature_importance()
    degenerate = model.degenerate_features(train)

    # A re-ranker that loses to one of its own input features is a real outcome on some feature
    # sets, not an impossible one -- but it is the kind of result that reads as a bug if it is
    # left for the reader to spot in a table, so say it here.
    best_baseline = max(
        ((name, metrics["auc"]["mean"]) for name, metrics in results.items()
         if not name.startswith("reranker")),
        key=lambda pair: pair[1], default=(None, None))
    reranker_auc = max(m["auc"]["mean"] for n, m in results.items() if n.startswith("reranker"))
    beats_baselines = best_baseline[0] is None or reranker_auc > best_baseline[1]

    print(f"\n=== {args.dataset}: test split, {test.n_impressions:,} impressions ===")
    header = f"  {'method':<32}" + "".join(f"{m:>22}" for m in METRICS)
    print(header)
    for name, metrics in results.items():
        row = f"  {name:<32}"
        for metric in METRICS:
            m = metrics[metric]
            row += f"{m['mean']:>10.4f} [{m['ci_low']:.3f},{m['ci_high']:.3f}]"
        print(row)

    if not beats_baselines:
        print(f"\n  !! the re-ranker ({reranker_auc:.4f} AUC) does NOT beat its best input "
              f"feature, {best_baseline[0]} ({best_baseline[1]:.4f}).")
        print("     On a feature set dominated by one strong signal with near-random companions, "
              "LambdaRank\n     can overfit the weak ones; check whether the strong features were "
              "excluded (--submission-safe).")
    if degenerate:
        print(f"\n  note: {len(degenerate)} feature(s) have no variance on this dataset and "
              f"cannot inform a split:\n     {', '.join(degenerate)}")

    print("\n  top features by gain:")
    for name, share in importance[:10]:
        print(f"    {name:<26} {share:6.1%}")

    payload = {
        "dataset": args.dataset,
        "submission_safe": args.submission_safe,
        "n_features": len(train.feature_names),
        "feature_names": train.feature_names,
        "n_train_impressions": train.n_impressions,
        "n_test_impressions": test.n_impressions,
        "best_iteration": model.booster.best_iteration,
        "train_seconds": round(train_s, 1),
        "params": model.params,
        "metrics": results,
        "beats_best_input_feature": bool(beats_baselines),
        "best_input_feature": best_baseline[0],
        "degenerate_features": degenerate,
        "feature_importance": [{"feature": n, "gain_share": s} for n, s in importance],
    }
    suffix = "_submission_safe" if args.submission_safe else ""
    out_dir = args.results_dir / args.dataset
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"rerank_before_after{suffix}.json").write_text(json.dumps(payload, indent=2))
    model.save(args.models_dir / args.dataset / f"reranker{suffix}.lgb")
    print(f"\n-> {out_dir / f'rerank_before_after{suffix}.json'}")
    print(f"-> {args.models_dir / args.dataset / f'reranker{suffix}.lgb'} (git-ignored)")
    comparison = write_comparison(args.results_dir)
    if comparison:
        print(f"-> {comparison}")


if __name__ == "__main__":
    main()
